[package]
name = "touringbuddy_rust"
version = "0.1.0"
authors = ["selimkaelin <selimkaelin@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.5"
serde = "1.0.120"
serde_derive = "1.0.120"